apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-local
    url: http://prometheus:9090
    isDefault: true
    access: proxy

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-local
    access: proxy
    jsonData:
      server: ch-clickhouse-0
      port: 8123
      username: default
      defaultDatabase: default
      protocol: http
    secureJsonData:
      password: ''
